FROM quay.io/debezium/connect:3.4

USER root
RUN mkdir -p /kafka/etc && \
    curl -fSL -o /kafka/etc/jmx_prometheus_javaagent.jar \
    https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/1.0.1/jmx_prometheus_javaagent-1.0.1.jar && \
    chmod 644 /kafka/etc/jmx_prometheus_javaagent.jar
USER kafka

COPY jmx-exporter/debezium-jmx-config.yml /kafka/etc/jmx-config.yml

ENV KAFKA_OPTS="-javaagent:/kafka/etc/jmx_prometheus_javaagent.jar=7072:/kafka/etc/jmx-config.yml"
